---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    {{- include "dragonfly-operator.labels" . | nindent 4 }}
    control-plane: controller-manager
  name: {{ include "dragonfly-operator.namespace" . }}