---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "dragonfly-operator.fullname" . }}-leader-election-rolebinding
  namespace: {{ include "dragonfly-operator.namespace" . }}
  labels:
    {{- include "dragonfly-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dragonfly-operator-leader-election-role
subjects:
- kind: ServiceAccount
  name: {{ include "dragonfly-operator.serviceAccountName" . }}
  namespace: {{ include "dragonfly-operator.namespace" . }}