apiVersion: v1
kind: Service
metadata:
  name: {{ include "dragonfly-operator.fullname" . }}-controller-manager-metrics-service
  namespace: {{ include "dragonfly-operator.namespace" . }}
  labels:
    {{- include "dragonfly-operator.labels" . | nindent 4 }}
    control-plane: controller-manager
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    control-plane: controller-manager
