---
name: devcontainer
on:
  push:
    branches:
      - '**'
      - '!main'
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

jobs:
  devcontainer-test:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' || (github.repository_owner != github.event.pull_request.head.repo.owner.login && github.event.pull_request.draft != true)
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.5
        with:
          submodules: true

      - name: Build and run dev container task
        uses: devcontainers/ci@v0.3.1900000349
        with:
          runCmd: ct lint --config .github/ct.yaml --charts charts/renovate
          env: GITHUB_TOKEN
        env:
          GITHUB_TOKEN: ${{ github.token }}